---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: buluma.openjdk
      tags: openjdk

    - name: include role
      ansible.builtin.include_role:
        name: ansible-role-confluence
      tags: confluence
