---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "confluence-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
    published_ports:
      - 8090/tcp
      - 8443/tcp
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
