---
- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: check port
      ansible.builtin.wait_for:
        port: "8090"
        timeout: "300"
        delay: "10"
      async: "300"
      poll: "10"
      register: result
      until: result is succeeded
      retries: 30

    - name: check page
      ansible.builtin.uri:
        url: "http://localhost:8090"
        status_code: "200"
        timeout: "300"
        return_content: true
      async: "300"
      poll: "10"
      register: result
      until: result.status == 200
      retries: 30

    - name: check result
      ansible.builtin.fail:
      when: "'confluence' not in result.content"
