---
- hosts: all
  remote_user: root
  become: true
  tasks:
     - name: check if ports are open
       ansible.builtin.wait_for:
          port: "{{ item }}"
          timeout: 2
       loop:
          - "8090"
       changed_when: false
       failed_when: false

     - name: see if the sample page returns 200
       ansible.builtin.uri:
          url: "http://127.0.0.1:8090/"
          return_content: yes
       changed_when: false
       register: result
       failed_when: false
