---
- hosts: all
  remote_user: root
  become: true
  tasks:

    - name: check web ui
      ansible.builtin.uri:
        url: "http://localhost:8090"
        return_content: yes
      register: confluence_check_web_ui
      failed_when:
        - "'confluence' not in confluence_check_web_ui.content"
